### ISSUE TITLE
Practica05TopicosA_JudithReynaCruzSantiago_4US

### ISSUE THREAD

**Issue by JudithReynaCS** [SistemasTecTlaxiaco/diseno-de-control-para-cajas-de-texto-JudithReynaCS#2]
[CALCULADORAIMC.zip](https://github.com/SistemasTecTlaxiaco/diseno-de-control-para-cajas-de-texto-JudithReynaCS/files/8339229/CALCULADORAIMC.zip)
[Practica05_JudithReynaCruzSantiago.pdf](https://github.com/SistemasTecTlaxiaco/diseno-de-control-para-cajas-de-texto-JudithReynaCS/files/8339234/Practica05_JudithReynaCruzSantiago.pdf)

**Comment by Adry117** [comment]
Calificación 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado.
